### ISSUE TITLE
no generative task?

### ISSUE THREAD

**Issue by rajarsheem** [google-research/multilingual-t5#26]
_Not an issue, but a general question:_

In the paper, all the tasks for which results are reported are discriminative in nature. I didn't find any results for a generative task whereas the original monolingual t5 showed results on both discriminative and generative tasks.

Any particular reason?

**Comment by craffel** [comment]
Hi Rajarshee, it was mainly because existing cross-lingual benchmarks tend to focus on non-generative tasks. Exceptions include machine translation (which was not a target for us, particularly since better results can probably be attained from backtranslation than unsupervised pre-training) and MLSUM (https://arxiv.org/abs/2004.14900) which has an ambiguous data license that prevented us from being able to use it. If you are aware of other good multi-/cross-lingual generative benchmarks, please let us know.

**Comment by rajarsheem** [comment]
sorry for the late reply @craffel . So, umm... why not [XGLUE](https://microsoft.github.io/XGLUE/). You may check out QG and News Title Generation over there. I am sure you would like to benchmark on these two NLG tasks for a start.
